services:
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  api.database:
    image: postgres:latest
    container_name: api.database
    environment:
      - POSTGRES_DB=Lists2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=malymimek
    ports:
      - 5432:5432
